version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: lojavirtual
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lojavirtual
    ports:
      - "5432:5432"
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      - postgres

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin-lojavirtual
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#    restart: always
#    depends_on:
#      - lojavirtual_db
#    networks:
#      - postgres
#    ports:
#      - "8081:80"
volumes:
    dbdata:
networks:
  postgres:
    driver: bridge