version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_lojavirtual
    networks:
      - host
    environment:
      POSTGRES_PASSWORD: loja
      POSTGRES_DB: lojavirtual

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-lojavirtual
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    restart: always
    depends_on:
      - db
    networks:
      - host
    ports:
      - "8081:80"

networks:
  postgres:
    driver: bridge